services:
  api: 
    # build: .
    image: estifo/restaurant-api:1.0      # pull from docker hub after we pushed our dockerfile
    container_name: Myrestaurant-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - restaurant-network

  postgres:
    image: postgres:17-alpine
    container_name: Mypostgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - restaurant-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.5-alpine
    container_name: Myredis
    restart: always
    ports:
      - "6379:6379"

    networks:
      - restaurant-network
    volumes:
      - redis-data:/data

networks:
  restaurant-network:

volumes:
  postgres-data:
  redis-data:
